### ISSUE TITLE
'missing: third party data' is not accepted as value for 'country' or 'collection_date'

### ISSUE THREAD

**Issue by bmschoene** [enasequence/webin-cli#103]
According to https://ena-docs.readthedocs.io/en/latest/faq/spatiotemporal-metadata.html, submitters will need to include values for `country` and `collection_date` in their sequence submissions (ASAP, but mandatory starting June 1st 2023). 

This seems to work fine, as long as valid values are provided.

**However, the reporting of missing values does not seem to be accepted.**

I just tried calling webin-CLI with the following command:

`java -jar webin-cli-6.4.0.jar -context sequence -manifest PRJEB61873_20230505123912_manifest.txt -userName **** -password **** -centerName "****" -inputDir DIR_PATH -outputDir DIR_PATH -test -validate`

The input files were the following:
- [PRJEB61874_20230505124638_manifest.txt](https://github.com/enasequence/webin-cli/files/11405557/PRJEB61874_20230505124638_manifest.txt)
- [PRJEB61874_20230505124638_flatfile.txt](https://github.com/enasequence/webin-cli/files/11405559/PRJEB61874_20230505124638_flatfile.txt)

So I annotated both fields as "missing: third party data":

![image](https://user-images.githubusercontent.com/43027482/236441450-640c806d-4747-40c4-88ca-ae32c048fca0.png)
Which, according to https://www.insdc.org/submitting-standards/missing-value-reporting/ and https://www.ebi.ac.uk/ena/browser/view/ERC000022 should be valid for both fields.

However, I get an error:
`ERROR: Submission validation failed because of a user error. Please check validation reports for further information: DIR_PATH\sequence\PRJEB61874_20230505124638_filesub\validate`

And the flatfile report tells me:
`ERROR: Feature qualifier "collection_date" has invalid date i.e.missing:thirdpartydata. [ line: 14 of PRJEB61874_20230505124638_flatfile.txt.gz]
ERROR: Feature qualifier "country" does not contain one of the permitted values - "missing" is not permitted. [ line: 13 of PRJEB61874_20230505124638_flatfile.txt.gz]
ERROR: Feature qualifier "country" does not contain one of the permitted values - "missing" is not permitted. [ line: 13 of PRJEB61874_20230505124638_flatfile.txt.gz]`

So, for some reason, the `missing: third party data` does not seem to be parsed correctly.

These are the error reporting files:
- [PRJEB61874_20230505124638_flatfile.txt.gz.report](https://github.com/enasequence/webin-cli/files/11405614/PRJEB61874_20230505124638_flatfile.txt.gz.report.txt) from validate folder
- [webin-cli.report](https://github.com/enasequence/webin-cli/files/11405615/webin-cli.report.txt) from validate folder
- [webin-cli.report](https://github.com/enasequence/webin-cli/files/11405629/webin-cli.report.txt)  from DIR_PATH

(each file manually extended with .txt to be uploadable here)

**As the time frame until this becomes mandatory is very short, please let me know how to fix this ASAP!**

Either I'm reading the documentation on how to correctly fill these fields for missing values wrong - in that case: what is the correct way? And please document that somewhere findable! - or there is a bug in Webin-CLI.

**Comment by bmschoene** [comment]
**This is really urgent!** 

I do not want to ship software without having verified that it works, and Webin-CLI is part of that software! So until this is resolved, I cannot build, test and ship the new version of my software, which means my users will be unable to submit alleles to ENA starting June. :(

**Comment by raskoleinonen** [comment]
Apologies for not noticing this issue sooner. We are working to resolve the problem and expect to have a fixed Webin-CLI version deployed no later than next week.

**Comment by raskoleinonen** [comment]
We have deployed a new Webin-CLI version to resolve this problem:

https://github.com/enasequence/webin-cli/releases/tag/6.4.1

The Webin-CLI will display the following message that explains the fix:

If you are using INSDC missing value terms (https://www.insdc.org/submitting-standards/missing-value-reporting/) please upgrade to Webin-CLI version 6.4.1 or later to avoid validation errors for country, collection_date, and lat_lon source feature qualifiers. The missing value terms are not yet supported by the flat file feature table. Webin-CLI version 6.4.1 will ignore missing value terms to avoid these errors.

**Comment by bmschoene** [comment]
This seems to work, thanks for the fix!

I have a question, though: what exaclty does "The missing value terms are not yet supported by the flat file feature table." mean? Are the values in these fields passed on to the database (but not validated) or completely removed? 
I.e., will Webin CLI 6.4.1 still be working June 1st (when these fields are supposed to become mandatory and submissions without them are rejected)?

Because I'd rather wait another week and get a Webin CLI version that will actually work instead of having to build yet another version two weeks later when you release the new Webin CLI version...

**Comment by raskoleinonen** [comment]
Thank you for the confirmation that the fix worked for you. 

I expect that the missing value terms will be supported in flat files from October 2023 onwards. We would change Webin-CLI at this time to inject the missing value terms from samples into the flat file source features. These terms are currently ignored as of Webin CLI 6.4.1 and if detected corresponding /country, /collection_date, and /lat_lon source qualifiers are not injected into flat files. The October 2023 change to Webin CLI will be transparent from the submitters' perspective. The only change is that the /country, /collection_date, and /lat_lon source qualifiers will be injected into flat file source features with the missing value terms.

**Comment by bmschoene** [comment]
Ah, I see. Thanks for the explanation.

But will the sequences be accepted without the removed spatiotemporal data? I thought these become mandatory from June 1st on?
