### ISSUE TITLE
Add "test" info to cli report file

### ISSUE THREAD

**Issue by ikostadi** [enasequence/webin-cli#11]
I did a successful test submission, i.e. used the combination `-submit -test`. The last line of the CLI report file reads (accession masked on purpose):

> INFO : The submission has been completed successfully.  The following analysis accession was assigned to the submission: ERZXXXXXX

The report does not contain any hint that this was a test submission. I had to review the receipt.xml to make sure the submission was indeed a test. Having that information directly in the CLI log would be helpful.

**Comment by raskoleinonen** [comment]
OK, we will do this.

**Comment by ikostadi** [comment]
Great, thanks!

**Comment by raskoleinonen** [comment]
Different confirmation message is now shown for -test submission:

https://github.com/enasequence/webin-cli/releases/tag/v1.8.6
