### ISSUE TITLE
Unable to upload/validate samples in project/sample set to private

### ISSUE THREAD

**Issue by GregDeakin** [enasequence/webin-cli#113]
Title says it all. 

I'm pretty certain this worked in older versions of the client (webin-cli-4.3.0.jar).

Part of the validation process seems to be to try and get info from https://www.ebi.ac.uk/biosamples/v2/samples/"SAMPLENAME"

This returns an error if the sample is set to private:

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Fri Feb 09 14:14:56 GMT 2024
There was an unexpected error (type=Forbidden, status=403).
This sample is private and not available for browsing. If you think this is an error and/or you should have access please contact the BioSamples Helpdesk at biosamples@ebi.ac.uk

Example of failure 

INFO : Your application version is 7.0.0                                                                                                                                                                                                    INFO : GETing https://www.ebi.ac.uk/biosamples/v2/samples/SAMEA115285375                                                                                                                                                                    INFO : Creating report file: /projects/oldhome/deakig/projects/sequence_files_backed_up/lauren/ena_upload/fastq/../submit/./webin-cli.report                                                                                                
INFO : Expiry of JWT is : Fri Feb 09 18:22:51 GMT 2024                                                                                                                                                                                      INFO : Refresh set to : Fri Feb 09 17:22:51 GMT 2024                                                                                                                                                                                        INFO : jwt = Optional[eyJhbGciOiJSUzI1NiJ9.eyJwcmluY2lwbGUiOiJXZWJpbi00MDE3MCIsInJvbGUiOlsiTUVUQUdFTk9NRV9BTkFMWVNJUyJdLCJleHAiOjE3MDc1MDI5NzEsImlhdCI6MTcwNzQ4NDk3MX0.rJNIkckUEA1fK7pJCA1Au4npsTdWPUE9ehfanUp9iKXfztbMaBmnQmmIyeB-8wOEQXmVV9_WdtYrYoEX82U9R_d83K1JQVc8KmXQiiBkX3KXlZI4Nco59tc68SP4HdlvkYvTvZux9koDnNKzHn-hUdlVeAOKkfJrAmc1S4U2Pc8FBZ7hVOjiHNQrDiq8xquvktFD4OCQzlXbN6bUjQkNX5vKhw5MkWj9-EQeV8joFjjry6pHcKEjvRoYh2DPMQKFh799hyuzT3CvVBdOrTcls8gRHziPFI9yC4ng0oGbygv5XRXK8Iu2KYafNv6kd1v1yQoBOUhmGYDD4h1mQerD5w]                                                                                                                                                                                                      ERROR: Failed to initialise validator. Could not retrieve BioSample [SAMEA115285375]                                                                                                                                                        ERROR: Failed to initialise validator. Could not retrieve BioSample [SAMEA115285375]

**Comment by tybonic** [comment]
I am facing exactly the same error with webin-cli-7.0.0.jar and my samples set to private.

**Comment by cocathail** [comment]
Hi there,

Webin-CLI does not support updating of metadata.

As per our documentation, ENA metadata objects can only be updated via interactive Webin (web interface) or programatically.

https://ena-docs.readthedocs.io/en/latest/update/metadata.html

Kind Regards,
Colman
The ENA Team

**Comment by tybonic** [comment]
Hi Colman,

Thanks for your quick reply. In my understanding, I do not use the Webin-CLI for updating metadata. I am trying to upload fastq files running the following command in the directory which contains fastq and manifest.txt files:

```{bash}
my_java="/usr/java/jre1.8.0_401/bin/java"
$my_java -version

echo ""

for Sample in $(ls *_manifest.txt | sed 's/_manifest.txt//g'); do
    echo "${Sample}_manifest.txt"
    $my_java -jar /vol/data/data_shared/software/ena_webin_cli/webin-cli-7.0.0.jar \
                    -userName Webin-***** \
                    -password "********" \
                    -manifest "${Sample}_manifest.txt" \
                    -context reads \
                    -inputDir ./ \
                    -outputDir ./webin_cli_out  \
                    -validate
    
    echo ""
done
```

Here are the first lines of the output:

```
java version "1.8.0_401"
Java(TM) SE Runtime Environment (build 1.8.0_401-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.401-b10, mixed mode)

blank_oemik_exp_010_manifest.txt
INFO : Your application version is 7.0.0
INFO : GETing https://www.ebi.ac.uk/biosamples/v2/samples/SAMEA115291442
INFO : Creating report file: /vol/data/data_tybonic/field_2021_batch1_v2/01_data/ena_submission/./webin_cli_out/./webin-cli.report
INFO : Expiry of JWT is : Tue Feb 13 19:54:23 UTC 2024
INFO : Refresh set to : Tue Feb 13 18:54:23 UTC 2024
INFO : jwt = Optional[eyJhbGciOiJSUzI1NiJ9.eyJwcmluY2lwbGUiOiJXZWJpbi02NjgyMyIsInJvbGUiOlsiTUVUQUdFTk9NRV9BTkFMWVNJUyJdLCJleHAiOjE3MDc4NTQwNjMsImlhdCI6MTcwNzgzNjA2M30.WgohbCrnYfOJSKQIZjgW6By21xUZDt76oyTjyNND8rSvgRRPCSVRSFrfsx9_vGxUfWJfFt9pEr-toMMyF725cjSeJ9c9I_EtI-9JIZ_YZtQOYhArh8ao_aM2-GYAipl7CRPOSc5_OXmSAcNXzvYANrSAH8W5OKhQaLIiQC7osnCfo5lW72T3bGa017yH59jI0cRz3y4AEvSys7xkqr1r__Tz9O_DYq-ZmlPM1NIJ0r_XvC8tu0F3387DTAUxfBpFpZ-xkwbniZLwtqbrNARmQalslfaXlaBmR6V5rIWPBVSsKixKLUxhiv2JZdTYSkrU4wbDTH0_fm00eUhHDlcbWQ]
ERROR: Failed to initialise validator. Could not retrieve BioSample [SAMEA115291442]
ERROR: Failed to initialise validator. Could not retrieve BioSample [SAMEA115291442]
```

The error occurs for all samples. The project accession and sample accessions in the manifest files are correct and I can see the project and sample accessions in the studies and samples reports on the web GUI.

This is an example on how my manifest files look:

```
name blank_oemik_exp_010
sample ERS18275357
study PRJEB*****
instrument Illumina iSeq 100
library_name oemik_exp_010
library_source METAGENOMIC
library_selection PCR
library_strategy AMPLICON
FASTQ 16s-Oemik-000811_S87_L001_R1_001.fastq.gz
```

**Comment by GregDeakin** [comment]
The issue is not with updating metadata, but with uploading fastq files.

It is not possible to upload sample fastq files using the webin-cli if the sample status is private.

**Comment by tybonic** [comment]
With version 7.0.1 of the Webin-CLI it works fine. Many thanks!
