### ISSUE TITLE
Could not retrieve BioSample

### ISSUE THREAD

**Issue by ttubb** [enasequence/webin-cli#115]
Hi 👋 
Since yesterday I'm having trouble with submission through webin-cli (v7.0.0). When trying to upload reads (to the dev server), I get the following error:

```
Your application version is 7.0.0
GETing https://wwwdev.ebi.ac.uk/biosamples/v2/samples/SAMEA130829077
Creating report file: <path to my dir>/reads_idx205_dh_pe/./webin-cli.report
Expiry of JWT is : Wed Feb 14 18:19:05 UTC 2024
Refresh set to : Wed Feb 14 17:19:05 UTC 2024
jwt = <sometoken>
ERROR: Failed to initialise validator. Could not retrieve BioSample [SAMEA130829077]
ERROR: Failed to initialise validator. Could not retrieve BioSample [SAMEA130829077]
```

My manifest file looks like this:
```
STUDY   PRJEB71644
SAMPLE  ERS28162653
NAME    idx205_dh_pe
INSTRUMENT      Illumina HiSeq 1500
LIBRARY_SOURCE  METAGENOMIC
LIBRARY_SELECTION       RANDOM
LIBRARY_STRATEGY        WGS
INSERT_SIZE     300
FASTQ   reads_1.fastq.gz
FASTQ   reads_2.fastq.gz
```

I run the tool like this:
```
java -jar <path to my jar>/webin-cli-7.0.0.jar -context reads -userName <username> -password <password> -manifest reads_idx205_dh_pe/MANIFEST -outputDir clioutp -inputDir reads_idx205_dh_pe/ -test -submit
```

I can see the sample `SAMEA130829077` in the web interface on the dev server. And obviously the tool is able to correctly derive the accession `SAMEA130829077` from `ERS28162653` (the accession I put in the MANIFEST) through some query. But there is indeed no JSON to be found at `https://wwwdev.ebi.ac.uk/biosamples/v2/samples/SAMEA130829077`. The status of my study is public. The status of my samples is public. I have used the same method to successfully upload reads last week. 

Here is a logfile of one of my attempts: [webin-cli.report.txt](https://github.com/enasequence/webin-cli/files/14280256/webin-cli.report.txt)

**Comment by ilyasdc** [comment]
Same problem here: 
ERROR: Failed to initialise validator. Could not retrieve BioSample [SAMEA115292593]

**Comment by cocathail** [comment]
Hi,

There was a minor bug introduced in February to how the BioSamples were being fetched. A minor version release has been made to correct this. 

Please upgrade to version 7.0.1 to address the issue.

Kind regards,
Colman
The ENA Team
