### ISSUE TITLE
Hard-coded version number in suggestion to download latest version

### ISSUE THREAD

**Issue by ikostadi** [enasequence/webin-cli#12]
I used `webin-cli-1.7.2.jar` this morning to validate a submission and it promptly suggested to download the latest version '1.7.4'. I found the suggestion very helpful. However, when I went to download the latest release, it turned out 1.8.0 was already out, which leads me to believe the version in the message is hard-coded.
As a user, I would find it even more helpful if the CLI actually checks against GitHub which the latest version is and suggests the  really latest one.

**Comment by epaule** [comment]
I was running 1.8.2 and it suggested updating to 1.8.0 to have all the latest features

**Comment by raskoleinonen** [comment]
Could you please try running Webin-CLI again? I suspect that you were using the -test flag and when we changed the version information in production yesterday, we did not remember to make the same change in the test service (this change was automatically applied overnight).

The version numbers are not hard coded. They are retrieved every time the application runs from a web endpoint.

This is the production endpoint, e.g.:
https://www.ebi.ac.uk/ena/submit/drop-box/cli/1.8.0
https://www.ebi.ac.uk/ena/submit/drop-box/cli/1.8.2

This is the test endpoint, e.g.:
https://wwwdev.ebi.ac.uk/ena/submit/drop-box/cli/1.8.0
https://wwwdev.ebi.ac.uk/ena/submit/drop-box/cli/1.8.2

Tested webin-cli-1.8.0.jar and webin-cli-1.8.2.jar today with and without -test flag ->

java -jar .\webin-cli-1.8.0.jar
--------------------------------
INFO : Your application version is 1.8.0
INFO : A new application version is available. Please download the latest version 1.8.2 from https://github.com/enasequence/webin-cli/releases

java -jar .\webin-cli-1.8.2.jar
--------------------------------
INFO : Your application version is 1.8.2
