### ISSUE TITLE
ERROR: Submission validation failed because of a user error. 

### ISSUE THREAD

**Issue by wegnerce** [enasequence/webin-cli#13]
I'm currently trying to submit multiple annotated genome sequences using WebinCLI. I call WebinCLI as follows: 
```
java -jar webin-cli-1.8.0.jar -context sequence -manifest manifest_RHAL1_ann.txt -username ***@uni-jena.de -password ******* -outputdir RHAL1_ENA -validate
```
My manifest file contains only three fields as described in the documentation:

https://ena-docs.readthedocs.io/en/latest/cli_05.html

Whenever, I execute WebinCLI I ontain the following error:

```
ERROR: Submission validation failed because of a user error. Please check the report directory for the errors: flatfile file validation failed for ****
```
The corresponding report file tells me the following:
```
2019-05-07T10:54:50 ERROR: Block AC must occur exactly once [ line: 148630]
```

I'm happy about any feedback as I have no clue what is going on, my flatfiles look ok.

Best

Carl-Eric

**Comment by d-smirnov** [comment]
Hi Carl-Eric,

Could you please try to use 
https://github.com/enasequence/webin-cli/releases/tag/v1.8.2

--
Dmitriy

**Comment by wegnerce** [comment]
Hi Dimitri,
I was meanwhile able to resolve the error, the problem was more on my side as I used the wrong submission type (annotated sequence instead of genome assembly).

Nonetheless, thanks for looking into this.

Best

Carl-Eric
