### ISSUE TITLE
Invalid submission account user name or password.

### ISSUE THREAD

**Issue by xvazquezc** [enasequence/webin-cli#14]
Hi there,

I've been trying to use Webin-CLI for nearly a week but I always get errors such as:
```
ERROR: Failed to lookup study "PRJEBXXXXX". Invalid submission account user name or password.
ERROR: Failed to lookup sample "ERSXXXXXXX". Invalid submission account user name or password.
```
I tried login with both my Webin id and my registered email, with the same result. I have been using this account for a few years already.

The project I'm trying to submit to is still confidential. I don't know if that's an issue. I know it exists because I received the confirmation from ENA.

I have tried with several `webin-cli` versions (1.8.3, 1.8.4, 1.8.5), 3 different Linux computers: a desktop with Ubuntu 16.04.01 and Java 1.8.0_212, a HPC with CentOS 6.10 with Java 1.8.0_101, and a HPC with CentOS 6.3 and Java 1.8.0_201. In all cases with the same result.

I don't know if you encountered any similar issue, but any help would be appreciated. I contacted ENA but no response so far...

Regards,
Xabi

**Comment by raskoleinonen** [comment]
Hi Xabi,

This error suggests that the provided username and password are not accepted by Webin. I have double checked that the Webin-CLI authentication appears to be working correctly.

1. Could you please double check that you can login into Webin Portal using you username and password:
https://www.ebi.ac.uk/ena/submit/webin/login

2. Could you please check that your Webin-CLI command like look similar to:

-test -userName=XXX -password=YYY -context=ZZZ -manifest=VVV -validate
or * 1
-test -userName XXX -password YYY -context ZZZ -manifest VVV -validate

*1 Either space or equals symbol can be used to separate options and values in Webin-CLI version 1.8.5.

3. Could you please check if your username or password has any characters that should be escaped in the shell you are using?

Best,
Rasko

**Comment by xvazquezc** [comment]
Thanks Rasko.

it was a special character in the password. It works by escaping it as you suggested, or by quoting it (both single and double quotes work).

**Comment by raskoleinonen** [comment]
Hi Xabi,

Great, thanks for letting me know that you can login now.

**Comment by ljchueca** [comment]
Hi there,

I am using Webin-CLI (webin-cli-3.2.2.jar) to submit raw reads to ENA but I have the next error:

`ERROR: Invalid submission account user name or password. Please try enclosing your password in single quotes`

I tried with single and double quotes but I have always the same error. I checked that I can log in to the Webin portal with this credentials. Moreover, I used a month ago the same credentials with the version webin-cli-3.2.1.jar but I have now the same error.

Many thanks,
Best,
Luis
