### ISSUE TITLE
Batch upload

### ISSUE THREAD

**Issue by mdehollander** [enasequence/webin-cli#18]
Is it possible to upload reads for multiple samples at once with the webin-cli? With the interactive submission you can upload fastq.gz files with ftp and then use a data spreadsheet to submit multiple samples at once. Am i right that you need to run `webin-cli` for every sample with a different manifest file? That feels a bit cumbersome to me.

**Comment by raskoleinonen** [comment]
Hi Mattias, 

Yes, currently Webin-CLI needs to be executed once for each submitted genome etc.  I have been thinking about supporting a spreadsheet where each row would correspond to one manifest file. Webin-CLI code base already contains some spreadsheet related functionality (it can generate Excel spreadsheet templates for the supported manifest files) but we have not had an opportunity to work further on this in the recent months. Also, there is a counterargument why the use of spreadsheets might not always be desirable. It may take a considerable time to validate a single submissions and having e.g. 1000 large genomes in a spreadsheet could take a very long time to complete unless we invest more time in Webin-CLI to support multi-threaded validation and submission.

Best,
Rasko

**Comment by mdehollander** [comment]
Hi Rasko,

Thanks for the quick reply. Good to hear that I did not miss anything. I will see if we can automate the creation of manifest files. For users with limited command line experience I foresee that submitting raw data files becomes a bit of a challenge.

**Comment by raskoleinonen** [comment]
I agree. This is why we still support interactive read submissions in https://www.ebi.ac.uk/ena/submit/sra
