### ISSUE TITLE
Assembly submission ASCII character issue

### ISSUE THREAD

**Issue by mb1069** [enasequence/webin-cli#20]
Hi, I'm trying to submit an assembly of ERR2114807 and am receiving a validation error;

> 2019-07-29T11:59:10 ERROR: Flatfile contains non-ascii characters: "leaf juice of 5g whole plantlets, briefly washed. Leaf juice was extracted via squashing in a pasta machine. Orr J, Haselkorn R. 1982. Regulation of glutamine synthetase activity and synthesis in free-living and symbiotic Anabaena spp. J Bacteriol 152: 626â635.".

The manifest file in question is;
> STUDY   ERP116553
SAMPLE  ERS1909481
ASSEMBLYNAME    ERR2114808
ASSEMBLY_TYPE   primary metagenome
COVERAGE        80
PROGRAM spadesv3.11.1
PLATFORM        NextSeq 500
MOLECULETYPE    genomic DNA
DESCRIPTION     ERP021566
FASTA  <hidden> ERR2114808.fasta.gz
TPA     true

Is it possible this is being retrieved from the ENA's database directly?

**Comment by raskoleinonen** [comment]
Yes, the offending text is retrieved from the sample ERS1909481. I have changed the sample text (626â635 to 626-635) in our production database. Could you please try to submit again?

**Comment by mb1069** [comment]
That worked, thank you!
The same issue is also occurring for ERR2114807 and ERR2114809, if you could take a look at those?

**Comment by raskoleinonen** [comment]
Could you please let me know the samples associated with the ERR2114807 and ERR2114809 submissions?

**Comment by mb1069** [comment]
ERS1909482 and ERS1909480

**Comment by raskoleinonen** [comment]
Changed these two samples as well. Could you please try submitting again?

**Comment by mb1069** [comment]
All sorted, thank you!
