### ISSUE TITLE
Upload failed due to system error

### ISSUE THREAD

**Issue by peritob** [enasequence/webin-cli#23]
Hello, I am trying to upload 27 SMRT cell read files. It seems they have to be loaded individually with separate manifest files.

Three questions:

1. After 3 hours the first file sent this error report. NB I have version 1.8.12 installed

INFO : Files have been uploaded to webin.ebi.ac.uk.
ERROR: In run, alias:"webin-reads-APSI1", accession:"". File "webin-cli/reads/APSI1/m54078_170628_032005.subreads.bam" does not exist in the upload area. The submission has failed because of a system error.

2. Can I upload bax.h5 data? It appears that only BAM, CRAM and FASTQ accepted? I would rather upload original data than processed.

3. I have two haploid genome assemblies based on primary and secondary (diploid)  genomes. I am unable to load the secondary genome using the context=genome command. How should I proceed?

many thanks,
Peri

**Comment by sholt6** [comment]
Thanks for your query Peri, I have provided responses in our existing RT ticket, #374676

**Comment by timyerg** [comment]
Hello!

> Thanks for your query Peri, I have provided responses in our existing RT ticket, #374676

Is there any way to read the discussion?
I encountered the same error but the only thread I found regarding the issue is this one and there is no answer to it.
