### ISSUE TITLE
abutting update

### ISSUE THREAD

**Issue by rob123king** [enasequence/webin-cli#28]
I'm still getting the abutting error with latest 2.2.4 version

ERROR: Abutting features cannot be adjacent between neighbouring exons. [ line: 533 of FC_Mitochondria.embl.gz]

**Comment by raskoleinonen** [comment]
Could you please send me the flat file (e.g. email to rasko@ebi.ac.uk or upload to webin.ebi.ac.uk using FTP) so that we can look further into this?

**Comment by rob123king** [comment]
the commits have been pushed now so works fine
