### ISSUE TITLE
Sporadic authentication errors

### ISSUE THREAD

**Issue by johnomics** [enasequence/webin-cli#31]
Hello,

I am getting authentication errors sporadically. Rerunning the same command works. Three consecutive commands:
```
[ena_submission] 2020-09-23 11:07 $ java -jar webin-cli-3.1.0.jar -ascp -userName='Webin-XXXXX' -password='XXXXX' -context reads -validate -manifest=manifest.txt
INFO : Your application version is 3.1.0
INFO : For SARS-CoV-2 data submissions, users should contact us in advance of submission at virus-dataflow@ebi.ac.uk for specific advice on options and to access the highest levels of support.
^C
[ena_submission] 2020-09-23 11:07 $ java -jar webin-cli-3.1.0.jar -ascp -userName='Webin-XXXXX' -password='XXXXX' -context reads -validate -manifest=manifest.txt
ERROR: Invalid submission account user name or password. Please try enclosing your password in single quotes.
[ena_submission] 2020-09-23 11:08 $ java -jar webin-cli-3.1.0.jar -ascp -userName='Webin-XXXXX' -password='XXXXX' -context reads -validate -manifest=manifest.txt
INFO : Your application version is 3.1.0
INFO : For SARS-CoV-2 data submissions, users should contact us in advance of submission at virus-dataflow@ebi.ac.uk for specific advice on options and to access the highest levels of support.
```

I have 105 manifest files to upload, 97 of which validated fine, 8 of which failed with this error, but rerunning them worked fine. Similarly, attempts to submit produced some of these errors seemingly at random - they are not occurring consistently with any particular manifest files.

What could be causing these errors? Is there a way of avoiding them?

Many thanks
John

**Comment by raskoleinonen** [comment]
Sporadic errors suggest that one of the two load balanced Webin REST services or one of the two load balanced Webin Auth services may not be working as expected. Checked that everything looked to be working Wednesday 12.30. Do you still experience this problem? The services have been designed to self-recover with only one known Webin Auth exception.

**Comment by johnomics** [comment]
Thanks for checking so quickly - I can now run the same command ten times over without error. I'll try the proper submissions again, and just retry them if any of them fail. FYI the errors came in between 01:28 and 05:22 this morning, and were still happening at 10-11 am as above.

**Comment by abomba** [comment]
I have similar problem now. 04.12.20 I validated couple files and server gave me normal feedback but after that all responses until now are authentication errors. I have webin-cli-3.2.2 version.

**Comment by raskoleinonen** [comment]
The Webin authetication service is unavailable at the moment. We are investigating the underlying problem.
