### ISSUE TITLE
Genome sequence upload is hanging

### ISSUE THREAD

**Issue by zgoodwin** [enasequence/webin-cli#33]
Hi There, I was trying to upload a successfully validated genome sequence last Friday using `webin-cli-v3.1.0` and it appears to have been hanging on the "uploading file" step for 3 days. The cooresponding project in ENA is not being updated. Could someone tell me what the problem might be? Here are the logs so far:

```
INFO : Your application version is 3.1.0
INFO : For SARS-CoV-2 data submissions, users should contact us in advance of submission at virus-dataflow@ebi.ac.uk for specific advice on options and to access the highest levels of support.
INFO : Creating report file: /mnt/genomes/lh244_nrgene1_ena_upload/./webin-cli.report
INFO : Submission has not been validated previously.
INFO : The submission has been validated successfully.
INFO : Uploading file: /mnt/genomes/lh244_nrgene1_ena_upload/LH244_NRgene.fna.gz
```

**Comment by raskoleinonen** [comment]
Most likely a transient problem with the FTPS service. Could you please kill the Webin-CLI process and re-execute it?

**Comment by zgoodwin** [comment]
Killed and re-executed about 6 hours ago, same results. I am also behind a VPN... could that be why this is happening?

**Comment by raskoleinonen** [comment]
Thank you. I can see that Webin-CLI uploaded the following file yesterday:

md5: 52079a5e9d94e0313a000ea409b5c7d0
size:631371466 
time: Oct 20 17:44 
file: webin-cli/genome/Zm-LH244-REFERENCE-BAYER-1.0/LH244_NRgene.fna.gz

Is the file size correct? I would like to confirm if the file was uploaded in its entirety.

Would you consider to allow me to make the submission on your behalf? I could then inspect and correct any problems with the Webin-CLI. If you are happy with this approach, could you please send me (rasko@ebi.ac.uk) the manifest file and the Webin-CLI command line options you were using? Please do *NOT* send me your password. If the LH244_NRgene.fna.gz was uploaded completely I can use it when attempting to resubmit.

Following outcomes are possible. The submission works for me. Then we should look more closely at your environment including the Java runtime you are using in case you are not using the Docker image. If the submission does not work for me then I will investigate and attempt to resolve any problems and deploy a new version of Webin-CLI.

**Comment by zgoodwin** [comment]
Yes, the file sizes match perfectly. I will e-mail you the command shortly.

**Comment by tpillone** [comment]
Hi,
I have a similar issue, the upload of genome files never ends. Were you able to solve this problem?

**Logs:**
INFO : Your application version is 3.1.0
INFO : For SARS-CoV-2 data submissions, users should contact us in advance of submission at virus-dataflow@ebi.ac.uk for specific advice on options and to access the highest levels of support.
INFO : Creating report file: /home/tpillone/work/projets/202010_ena_submission/./webin-cli.report
INFO : The submission has been validated successfully.
INFO : Uploading file: /home/tpillone/work/projets/202010_ena_submission/IT551_29614.fna.gz

I checked on the ftp, an empty file was created in the folder _webin-cli/genome/IT551_29614._

**Comment by raskoleinonen** [comment]
I have completed Zane's submission using Webin-CLI 3.1.0. We should look at the Java runtime version (java -version) next as this may affect Webin-CLI behaviour.

Summary of what might be going wrong:
- Transient problem with webin.ebi.ac.uk/webin2.ebi.ac.uk FTPS service. Unlikely if we see the problem more than a few times on different days.
- Problem with Java runtime in respect to the Java FTPS library. Can be investigated by testing with the Java runtime version that is known to have the problem.
- Firewall related problem. Most difficult to investigate as testing and debugging needs to be done inside the firewall.

Trestan, could you please let me know the Java runtime version you are using? Also, would you consider to allow me to make the submission on your behalf? I could then inspect and correct any problems with the Webin-CLI. If you are happy with this approach, could you please send me (rasko@ebi.ac.uk) the manifest file, upload other files to webin.ebi.ac.uk FTPS and provide me the Webin-CLI command line options you were using? Please do NOT send me your password. Could you also please confirm the Webin-N submission account you are using as I did not find the webin-cli/genome/IT551_29614 folder.

**Comment by tpillone** [comment]
I'm using a singularity container with the following java version:
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

I just sent you the fasta file, the manifest and the command line I used for the submission by email.

**Comment by raskoleinonen** [comment]
webin.ebi.ac.uk FTP was replaced by webin2.ebi.ac.uk FTPS in Webin-CLI 3.0.1. This is now the primary suspect for this problem. It is not clear from where this error originates. For example, the pre-build Webin-CLI docker image works in my environment but not in Trestan's.

**Comment by raskoleinonen** [comment]
We will release a new version of Webin-CLI with latest FTPS libraries. Let's see if this will help.
