### ISSUE TITLE
Invalid submission account webin-cli-3.2.2.jar

### ISSUE THREAD

**Issue by ljchueca** [enasequence/webin-cli#36]
Hi there,

I am using Webin-CLI (webin-cli-3.2.2.jar) to submit raw reads to ENA but I have the next error:

`ERROR: Invalid submission account user name or password. Please try enclosing your password in single quotes`

I tried with single and double quotes but I have always the same error. I checked that I can log in to the Webin portal with this credentials. Moreover, I used a month ago the same credentials with the version webin-cli-3.2.1.jar but I have now the same error.

Many thanks,
Best,
Luis

**Comment by raskoleinonen** [comment]
There is currently a problem with the Webin authentication service. To be specific, with the underlying Kubernetes cluster.  Webin authentication will not unfortunately work until this has been resolved.

**Comment by ljchueca** [comment]
Many thanks, 

It looks that is working now.

**Comment by raskoleinonen** [comment]
The Webin authentication service should now be fully operational again.
