### ISSUE TITLE
Validation error paired .fastq.bz2

### ISSUE THREAD

**Issue by Gama-Carvalho** [enasequence/webin-cli#42]
Hi,
I'm using Webin-Cli for the first time and getting the following validation error I cannot figure out:

![Screenshot 2021-02-12 at 00 24 07](https://user-images.githubusercontent.com/32682163/107716142-aad0c600-6cc8-11eb-90d0-e3c8fa62bed9.png)

First line of ae-RNAi_off_1_R1.fastq.bz2 after bunzip2 is:
@NB501289:75:HVHHYBGX3:1:11101:7995:1043 1:N:0:ATTACTCG

Thanks for your help!

**Comment by raskoleinonen** [comment]
Looking at the error message the decompression has been unsuccessful. Could you please try with gzip compression instead of bzip2 compression?

**Comment by raskoleinonen** [comment]
A fix has been deployed for bzip2 compression. 

Could you please try the latest version: https://github.com/enasequence/webin-cli/releases/tag/v3.7.0

**Comment by Gama-Carvalho** [comment]
Thank you!
In the meantime, as suggested, I changed the compression format and concluded the submission of my files, so I’m afraid I won’t be able to test this right now.
However, will definitely try the new version for .bz2 if chance appears in the near future.
Kind regards,
Margarida

__________________________________________________________________________

Margarida Gama-Carvalho, PhD
mhcarvalho@fc.ul.pt<mailto:mhcarvalho@fc.ul.pt> | +351 217 500 876
Group Leader, Gene Expression and Regulation
Assistant Professor, Dept. of Chemistry and Biochemistry
Faculdade de Ciências da Universidade de Lisboa
Edifício C8, Gabinete 8.3.11
Campo Grande
1749-016 Lisboa
Portugal
