### ISSUE TITLE
Upload never ends

### ISSUE THREAD

**Issue by maxbranger** [enasequence/webin-cli#48]
Hi,
following my submission process, I was able to validate my files before submission.
When I ask the software to submit, everything is ok EXCEPT that it is stuck at "Uploading"

INFO : Uploading file: MyFile.embl.gz

And nothing happends for hours...

The fact is that my file has been uploaded on FTP, but it doesn't work well.
I've also notice that validate and submission reports are all empty...

Hope you could help...
Thanks,

**Comment by DustinSokolowski** [comment]
Hey!

I've come across the same issue, any update?

**Comment by Charitini93** [comment]
Hey,
Sorry, I didn't find any solution for this. I had to mail them so they
would upload the sequence themselves. Just so you know, It can take them
around two weeks to reply...

**Comment by raskoleinonen** [comment]
We have deployed Webin-CLI version 6.0.0 with build-in FTP(S)/Aspera/HTTPS call retries and improved logging of these errors:
https://github.com/enasequence/webin-cli/releases/tag/6.0.0

This may insulate users from transient errors and will help us to diagnose the exact problem from the logs. For example, each different type of FTP(S) error can be identified from the logs.

Please upgrade to Webin-CLI version 6.0.0 and if you have further file upload problems please contact us preferably using (fastest response time):
https://www.ebi.ac.uk/ena/browser/support
