### ISSUE TITLE
nested exception is java.net.UnknownHostException

### ISSUE THREAD

**Issue by ljchueca** [enasequence/webin-cli#50]
Hi,

I'm trying to validate the data before submission with the next code:

`java -Xms4G -jar webin-cli-3.7.0.jar \
 -context=reads \
 -manifest=manifest_02.txt \
 -username="Webin-XXX" \
 -password="XXXXX" \
 -inputdir=/path/llumina_reads \
 -outputdir=/path/Illumina_reads \
 -validate`

but I am recovering this error:
`ERROR: I/O error on POST request for "https://www.ebi.ac.uk/ena/submit/webin/auth/login": www.ebi.ac.uk; nested exception is java.net.UnknownHostException: www.ebi.ac.uk`

Could anyone help me?
Thanks
Luis

**Comment by raskoleinonen** [comment]
Apologies for the very late answer. This error must have been a transient problem relating to the network connection to EBI.

Somewhat related to this is ->

We have deployed Webin-CLI version 6.0.0 with build-in FTP(S)/Aspera/HTTPS call retries and improved logging of these errors:
https://github.com/enasequence/webin-cli/releases/tag/6.0.0

This may insulate users from transient errors and will help us to diagnose the exact problem from the logs. For example, each different type of FTP(S) error can be identified from the logs.

Please upgrade to Webin-CLI version 6.0.0 and if you have further file upload problems please contact us preferably using (fastest response time):
https://www.ebi.ac.uk/ena/browser/support
