### ISSUE TITLE
Failed to upload files to webin.ebi.ac.uk because of a system error

### ISSUE THREAD

**Issue by msagniez** [enasequence/webin-cli#53]
Hi,

I'm facing some issues while trying to upload my RNA-seq file with webin-cli tool.
All my files (coupled with their own manifest files) have passed the test (with -validate option) but when changing the -validate option for -submit, the following error occurs:

INFO : The submission has been validated successfully.
ERROR: Failed to upload files to webin.ebi.ac.uk using FTP. Connection refused (Connection refused) Failed to upload files to webin.ebi.ac.uk because of a system error.

I saw that this error already happened in the issues using a previous version of the tool (sequencing data submission #38) and checked both the availability of port 21 and the connection to the server via FTP. Port 21 is available and I have succesfully connected to the webin2.ebi.ac.uk server using FTP and my webin username and password.

At this point do you know what I can do to resolve this error ?

**Comment by bio15anu** [comment]
I am also having this issue. Is this being addressed? In the meantime could we use an older version of the webin cli tool instead?

**Comment by RAWWiberg** [comment]
I'm getting a similar error:

```
INFO : Files have been uploaded to webin2.ebi.ac.uk.
ERROR: A server error occurred when attempting to submit. The submission has failed because of a system error.
```

The files validate just fine. And the first line above seem to indicate the files are in fact uploaded but then something goes wrong. In the "report" file there is this:

```
2022-03-14T03:16:53 INFO : Files have been uploaded to webin2.ebi.ac.uk. 
2022-03-14T03:17:56 ERROR: A server error occurred when attempting to submit. The submission has failed because of a system error.
uk.ac.ebi.ena.webin.cli.WebinCliException: A server error occurred when attempting to submit. The submission has failed because of a system error.
        at uk.ac.ebi.ena.webin.cli.WebinCliException.error(WebinCliException.java:88)
        at uk.ac.ebi.ena.webin.cli.WebinCli.submit(WebinCli.java:271)
        at uk.ac.ebi.ena.webin.cli.WebinCli.execute(WebinCli.java:199)
        at uk.ac.ebi.ena.webin.cli.WebinCli.__main(WebinCli.java:96)
        at uk.ac.ebi.ena.webin.cli.WebinCli.main(WebinCli.java:77)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: uk.ac.ebi.ena.webin.cli.WebinCliException: A server error occurred when attempting to submit.
        at uk.ac.ebi.ena.webin.cli.WebinCliException.systemError(WebinCliException.java:80)
        at uk.ac.ebi.ena.webin.cli.service.handler.DefaultErrorHander.handleError(DefaultErrorHander.java:45)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:777)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:669)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:578)
        at uk.ac.ebi.ena.webin.cli.service.SubmitService.doSubmission(SubmitService.java:113)
        at uk.ac.ebi.ena.webin.cli.WebinCli.submit(WebinCli.java:266)
        ... 11 common frames omitted

```

**Comment by raskoleinonen** [comment]
We have deployed Webin-CLI version 6.0.0 with build-in FTP(S)/Aspera/HTTPS call retries and improved logging of these errors:
https://github.com/enasequence/webin-cli/releases/tag/6.0.0

This may insulate users from transient errors and will help us to diagnose the exact problem from the logs. For example, each different type of FTP(S) error can be identified from the logs.

Please upgrade to Webin-CLI version 6.0.0 and if you have further file upload problems please contact us preferably using (fastest response time):
https://www.ebi.ac.uk/ena/browser/support

**Comment by raskoleinonen** [comment]
Thank you for reporting the error. The retries and improved error logs give us more information about the exact problem to help us to investigate further.

**Comment by KJKwon** [comment]
I'm also facing the same error (webin-cli-6.3.0.)

INFO : Uploading file: /work/kkwon/20230111_Data/230106_arrived/Sample_list/Set1_forward.fastq.gz
WARN : Retrying file upload to FTP server.
WARN : Retrying file upload to FTP server.
WARN : Retrying file upload to FTP server.
WARN : Retrying file upload to FTP server.
WARN : Retrying file upload to FTP server.
WARN : Retrying file upload to FTP server.
ERROR: Failed to upload files to webin.ebi.ac.uk using FTP. Connection or outbound has closed Failed to upload files to webin.ebi.ac.uk because of a system error.
ERROR: Failed to upload files to webin.ebi.ac.uk using FTP. Connection or outbound has closed Failed to upload files to webin.ebi.ac.uk because of a system error.

**Comment by raskoleinonen** [comment]
The webin.ebi.ac.uk FTP(S) service is noticeably unreliable. We are revising and improving the Webin-CLI FTP(S) file upload retry logic as we recently understood that if the (socket) connection is lost retrying will not be successful without re-establishing the FTP(S) connection. We are working to implement the behavior.

**Comment by tothuhien** [comment]
I had the same problem when trying to upload a file of nanopore sequences about 60G to ENA. Do you have any news on this? Thanks.

**Comment by bri-risk** [comment]
They never gave me an answer on if the webin-cli system was fixed. However, I figured out a workaround.

Go to this site https://ena-docs.readthedocs.io/en/latest/submit/fileprep/upload.html#appendix-configuring-your-firewall-for-ena-upload and follow the directions for 'using windows file explorer'. This is essentially creating a connection between your computer and their network. Once the file was created I simply pasted in my files and that gave ENA access to the sequencing. It takes a couple hours to copy/paste large files, but this seemed to work. Just make sure to email ENA and ask for confirmation of receipt to make the files public.


Bri Risk, MS, RD, CSSD
Board Certified Sports Dietitian
Food Scientist/Executive Chef
PhD Candidate
Integrative Cardiovascular & Intestinal Health Lab
Colorado State University

**Comment by raskoleinonen** [comment]
Webin-CLI uses FTP(S) or Aspera. The FTP(S) is known to have two main issues: (1) reliability problems and (2) firewall problems. The Aspera is understood to be more reliable.

We have worked to improve the FTP issue (1) by incrementally improving FTP retries in Webin-CLI. I think that the Webin-CLI 6.4.0 version now does everything it can including re-connecting if the FTP connection was lost for any reason (typically manifested as a socket error) while maintaining its state over the re-connection attempt. 

For the (2) firewall errors, we have a limited understanding ourselves how the firewalls may affect the FTP protocol or how to best resolve these problems. We acknowledge that an HTTP(S) based file upload protocol would be preferred, unfortunately, we are limited to using FTP(S) or Aspera at this time in the file upload backend.

**Comment by saat-mics** [comment]
Hi,

I am using Webin-Cli v6.4.1

and still getting same error:

INFO:    Using cached SIF image
INFO : Your application version is 6.4.1
INFO : If you are using INSDC missing value terms (https://www.insdc.org/submitting-standards/missing-value-reporting/) please upgrade to Webin-CLI version 6.4.1
or later to avoid validation errors for country, collection_date, and lat_lon source feature qualifiers. The missing value terms are not yet supported
by the flat file feature table. Webin-CLI version 6.4.1 will ignore missing value terms to avoid these errors.
INFO : Submission has not been validated previously.
INFO : Creating report file: /crex/proj/uppstore2017065/delivery02342/INBOX/P13257/P13257_137/02-FASTQ/190628_A00689_0043_BHKF75DSXX/./webin-cli.report
INFO : Processing file /crex/proj/uppstore2017065/delivery02342/INBOX/P13257/P13257_137/02-FASTQ/190628_A00689_0043_BHKF75DSXX/P13257_137_S39_L001_R1_001.fastq.gz
INFO : Collected 100000 reads [file: /crex/proj/uppstore2017065/delivery02342/INBOX/P13257/P13257_137/02-FASTQ/190628_A00689_0043_BHKF75DSXX/P13257_137_S39_L001_R1_001.fastq.gz]
INFO : Collected 1 read labels: [1] [file: /crex/proj/uppstore2017065/delivery02342/INBOX/P13257/P13257_137/02-FASTQ/190628_A00689_0043_BHKF75DSXX/P13257_137_S39_L001_R1_001.fastq.gz]
INFO : Has possible duplicate read name(s): false [file: /crex/proj/uppstore2017065/delivery02342/INBOX/P13257/P13257_137/02-FASTQ/190628_A00689_0043_BHKF75DSXX/P13257_137_S39_L001_R1_001.fastq.gz]
INFO : The submission has been validated successfully.
INFO : Connecting to FTP server : webin2.ebi.ac.uk
WARN : Retrying connecting to FTP server.
WARN : Retrying connecting to FTP server.
WARN : Retrying connecting to FTP server.
WARN : Retrying connecting to FTP server.
WARN : Retrying connecting to FTP server.
WARN : Retrying connecting to FTP server.
ERROR: Failed to connect to webin.ebi.ac.uk using FTP. Failed to upload files to webin.ebi.ac.uk because of a system error.
ERROR: Failed to connect to webin.ebi.ac.uk using FTP. Failed to upload files to webin.ebi.ac.uk because of a system error.

Any suggestion on how to make it run?

thanks,
Atal

**Comment by raskoleinonen** [comment]
If your organisation is using a proxy following these instructions might help: https://ena-docs.readthedocs.io/en/latest/submit/general-guide/webin-cli.html#configuring-your-firewall-for-ena-upload. 

The problem may also be related to firewall settings. In this case, the following instruction might help: https://ena-docs.readthedocs.io/en/latest/submit/fileprep/upload.html#appendix-configuring-your-firewall-for-ena-upload

**Comment by bri-risk** [comment]
Thank you for the email Mr. Leinonen. I conferred with the university IT department and they do not have firewalls set for outbound data, which I'd imagine is for instances such as this. Were there glitches in the software, or is the program currently functioning properly?

Bri Risk, MS, RD, CSSD
Board Certified Sports Dietitian
Food Scientist/Executive Chef
PhD Candidate
Integrative Cardiovascular & Intestinal Health Lab
Colorado State University

**Comment by raskoleinonen** [comment]
The Webin-CLI FTP code has been incrementally improved and should now have all possible FTP retries and error-handling routines. 

However, the underlying webin.ebi.ac.uk FTPS service may be unavailable at times. E.g. FTPS user authentication did not recently work for a small number of users for an extended period of time. If the Webin-CLI does not work, and especially if direct use of the webin.ebi.ac.uk FTP(S) fails as well, then there is likely to be a problem with the webin.ebi.ac.uk FTPS service that needs to be addressed.

**Comment by bri-risk** [comment]
Hi Atal,

I don't work for ENA so I'm not sure how to address your issue.

Bri Risk, MS, RD, CSSD
Board Certified Sports Dietitian
Food Scientist/Executive Chef
PhD Candidate
Integrative Cardiovascular & Intestinal Health Lab
Colorado State University

**Comment by raskoleinonen** [comment]
Dear Atal,

The "Read type information missing in run" error indicates that more than two Fastq files are included in one Webin-CLI reads submission or in one Webin REST run XML submission.

When using Webin-CLI, please use a JSON manifest as described here:
https://ena-docs.readthedocs.io/en/latest/submit/reads/webin-cli.html#json-manifest-file-format

The JSON read_type attribute supports the following values:
- single
- paired
- cell_barcode
- umi_barcode
- feature_barcode
- sample_barcode
- spatial_barcode

Best wishes,
Rasko

**Comment by saat-mics** [comment]
Thanks a lot, that solved the problem.

Cheers,
Atal

**Comment by raskoleinonen** [comment]
Hi Atal,

I will shortly update the instructions page to show:
```
{
 "study": "TODO",
 "sample": "TODO",
 "name": "TODO",
 "platform": "TODO",
 "instrument": "TODO",
 "insert_size": "TODO",
 "library_name": "TODO",
 "library_source": "TODO",
 "library_selection": "TODO",
 "library_strategy": "TODO",
```

Could you please first change the start of your JSON document to:
```
"study": ,"PRJEB62707",
"sample": "ERS15574205",
"name": "P9721_143",
"instrument": "Illumina NovaSeq 6000",
"insert_size": "350",
"library_source": "GENOMIC",
"library_selection": "RANDOM",
"library_strategy": "WGS",
```

You are missing parenthesis around the values and a comma after each field.

**Comment by saat-mics** [comment]
Thanks again, Rasko.

I have just added parenthesis and commas, but still getting same error. My script looks like below now:

{
"study":  "PRJEB62707",
"sample": "ERS15574205",
"name": "P9721_143",
"instrument": "Illumina NovaSeq 6000",
"insert_size": "350",
"library_source": "GENOMIC",
"library_selection": "RANDOM",
"library_strategy": "WGS",
"fastq": [
{
"value": "P9721_143_S43_L001_R1_001.fastq.gz",
"attributes": {
""read_type": "paired", "sample_barcode"
}
},
{
"value": " P9721_143_S43_L001_R2_001.fastq.gz",
"attributes": {
"read_type": "paired", "sample_barcode"
}
},
{
"value": "P9721_143_S43_L002_R1_001.fastq.gz",
"attributes": {
"read_type": "paired", "sample_barcode"
}
},
{
value: "P9721_143_S43_L002_R2_001.fastq.gz",
"attributes": {
"read_type": "paired", "sample_barcode"
}
}
]
}

**Comment by raskoleinonen** [comment]
Hi Atal,

There are several JSON formatting errors. The following is valid JSON, however, there is another issue I will explain below:
```
{
"study": "PRJEB62707",
"sample": "ERS15574205",
"name": "P9721_143",
"instrument": "Illumina NovaSeq 6000",
"insert_size": "350",
"library_source": "GENOMIC",
"library_selection": "RANDOM",
"library_strategy": "WGS",
"fastq": [
{
"value": "P9721_143_S43_L001_R1_001.fastq.gz",
"attributes": {
"read_type": ["paired", "sample_barcode"]
}
},
{
"value": "P9721_143_S43_L001_R2_001.fastq.gz",
"attributes": {
"read_type": ["paired", "sample_barcode"]
}
},
{
"value": "P9721_143_S43_L002_R1_001.fastq.gz",
"attributes": {
"read_type": ["paired", "sample_barcode"]
}
},
{
"value": "P9721_143_S43_L002_R2_001.fastq.gz",
"attributes": {
"read_type": ["paired", "sample_barcode"]
}
}
]
}
```

The "paired" read_type can only be used for exactly two fastq files in one reads context submission. You might wish to create two reads submissions, one for P9721_143_S43_L001* and another for P9721_143_S43_L002*.

**Comment by saat-mics** [comment]
Rasko, Thanks again for your help with this. I am no more getting the same error.

However, there are still errors. I have data for same individuals coming from 2 or more lanes.
As you suggested, I created two reads submissions, one for P9721_143_S43_L001* and another for P9721_143_S43_L002*.

but now that gives me other error:

ERROR: In experiment, alias: "webin-reads-P9721_143". The object being added already exists in the submission account with accession: "ERX11157306". The submission has failed because of a system error.
ERROR: In experiment, alias: "webin-reads-P9721_143". The object being added already exists in the submission account with accession: "ERX11157306". The submission has failed because of a system error.

The reason I am trying to use manifest.json is that I have more than 2 fastq files under same accession. How do I solve this problem, please?

thanks,
Atal

**Comment by raskoleinonen** [comment]
Hi Atal,

This error means that a reads submission has already been made with the same name using the submission account Webin-57425:

```
{
...
"name": "P9721_143",
...
```
Names are unique to prevent accidental re-submissions. Could you please make sure that all names are unique?

**Comment by saat-mics** [comment]
Hi Rasko,

Thanks for your reply.

I will try to explain it here again. So, for sample "P9721_143", I have 4 fastq files:
P9721_143_S43_L001_R1_001.fastq.gz
P9721_143_S43_L001_R2_001.fastq.gz
P9721_143_S43_L002_R1_001.fastq.gz
P9721_143_S43_L002_R2_001.fastq.gz

if i submit these files in 2 rounds, I still use the same "name" as these data belong to same individual. Should it not be the way to do it?

Atal

**Comment by raskoleinonen** [comment]
Hi Atal,

The name needs to be unique within a submission account so that each read submission has a different name. The name is not the sample name but the name for the files being submitted. e.g.  P9721_143_S43_L001 and P9721_143_S43_L002 could be possible names to use.

**Comment by saat-mics** [comment]
thanks again, Rasko.

So, this means that I will have to have accession id both for P9721_143_S43_L001 and P9721_143_S43_L002? As the same file name can be used for forward and reverse reads, I thought that would be possible even for reads from different lanes.

I have data from 60 individuals and I intended to use 60 different 'names', and 'id' for those 60 names have already been generated. but what i understand now is that I will need 120 ids. Probably its better to regenerate ids for files?

thanks,
Atal

**Comment by raskoleinonen** [comment]
Hi Atal,

if you have paired reads for 60 individuals, you would make 60 submissions with 60 unique "names"s. Each submission would contain two Fastq files representing the two reads in the pair.

Yes to -> have (unique and different) accession id for P9721_143_S43_L001 and P9721_143_S43_L002

Best wishes,
Rasko

**Comment by saat-mics** [comment]
Thanks very much, Rasko.

Samples were sequenced in 2 lanes (paired-end run). I am doing it like P9721_143_S43_L001 and P9721_143_S43_L002, and that seems working.

Thanks again,
Atal

**Comment by jorondo1** [comment]
Dear @raskoleinonen ,

I am getting a similar error than the one originally posted. 

```
INFO : Your application version is 7.2.1                                                                                                                                                
INFO : Please upgrade to Webin-CLI version 7.0.1 or later if you see the following error: Failed to initialise validator. Could not retrieve BioSample.                                 
INFO : Connecting to FTP server : webin2.ebi.ac.uk                                                                                                                                      
INFO : Creating report file: /home/def-ilafores/analysis/boreal_moss/ENA_submission/run_manifests/./webin-cli.report                                                                    
INFO : Uploading file: /home/def-ilafores/analysis/boreal_moss/preproc/S-11-POLJUN-G/S-11-POLJUN-G_paired_1.fastq.gz                                                                    
INFO : Uploading file: /home/def-ilafores/analysis/boreal_moss/preproc/S-11-POLJUN-G/S-11-POLJUN-G_unmatched_2.fastq.gz                                                                 
INFO : Uploading file: /home/def-ilafores/analysis/boreal_moss/preproc/S-11-POLJUN-G/S-11-POLJUN-G_unmatched_1.fastq.gz                                                                 
INFO : Uploading file: /home/def-ilafores/analysis/boreal_moss/preproc/S-11-POLJUN-G/S-11-POLJUN-G_paired_2.fastq.gz                                                                    
INFO : Files have been uploaded to webin2.ebi.ac.uk.                                                                                                                                    
ERROR: In run, alias: "webin-reads-Boreal Moss Microbiome S-11-POLJUN-G". Read type information missing in run. The submission has failed because of a system error.                    
ERROR: Some or all submissions failed. Please see application logs.                                                                                                                     
```


Before asking my sysadmin to address the firewall, I want to validate something regarding your comment earlier:

> The "Read type information missing in run" error indicates that more than two Fastq files are included in one Webin-CLI reads submission or in one Webin REST run XML submission.

I have used both the paired and unpaired sections of my reads for assembly, so naturally I want to submit all 4 fastqs for each samples (paired_1, paired_2, unpaired_1 and unpaired_2)

From reading the ENA docs I added four FASTQ fields in my manifest. Is this a good way to do it? or is there another way to submit four files per sample?

Thanks in advance

**Comment by mairaihsann** [comment]
Hi @jorondo1,

You can only submit 2 fastq files (forward R1 and reverse R2) for a paired fastq file submission. The manifest file only accepts a maximum of 2 FASTQ fields. Any unpaired reads can be included within the forward and reverse files - so your R1 file can contain the unpaired_1 sequences and the R2 file can contain the unpaired_2 sequences. When these files are processed, the ENA generates a forward file and reverse file (ERRxxx_1.fastq.gz and ERRxxx_2.fastq.gz) for the paired reads and a third file (ERRxxx_3.fastq.gz) containing only the unpaired reads. 

The only requirement in this case for paired read submissions is that the pairing percentage should not be less than 20%. Please also make sure your fastq files follow the format described here: https://ena-docs.readthedocs.io/en/latest/submit/fileprep/reads.html#fastq-format

Thanks,
Maira
