### ISSUE TITLE
ERROR: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by andreott** [enasequence/webin-cli#59]
Hi ena team,

I am verifying my flat file and webin-cli-4.1.0.jar (openjdk 11.0.12 2021-07-20) is giving me this error message 

> ERROR: Comparison method violates its general contract! [ line: 2824124 of filename.flat.gz]

The corresponding line in the flat file reads:
> ID   XXX; XXX; linear; genomic DNA; WGS; XXX; 40137130 BP.

It is not the first ID line and it does not show any significant difference to those not producing the error.

Any hints?

**Comment by snathanvj** [comment]
Hi @andreott ,

     Thanks for contacting us , could you please upload the submission file and manifest to our upload area and confirm , so that I can debug the issue. Also, could you please give me the project_id and sample_id please, if you are happy to paste the manifest file content here I can these information from there. 

How to upload files:
https://ena-docs.readthedocs.io/en/latest/submit/fileprep/upload.html

Thanks

**Comment by andreott** [comment]
Hello,

I have just uploaded a tar.gz archive (ENA_CHECK_UPLOAD.tar.gz).

This file contains:
- flat file
files to produce flat file:
- fasta file
- gff file
- manifest.txt
Upload error report:
- folder genome

The manifest.txt reads:
STUDY           ERP131809
SAMPLE          ERS7630965
ASSEMBLYNAME    PHOROB
ASSEMBLY_TYPE   isolate
COVERAGE        34
PROGRAM         Canu 2.1.1
PLATFORM        PromethION,NovaSeq
MOLECULETYPE    genomic DNA
RUN_REF         ERR6797440,ERR6740384
FLATFILE        phorob.flat.gz 

Project id: PRJEB47530
Sample Id: ERS7630965

The following commands were used to produce the flat file:

EMBLmyGFF3 --species 109678 --project_id PRJEB47530 --locus_tag PHOROB --data_class WGS --molecule_type "genomic DNA" --topology linear -r 1 phorob.gff3 phorob.fa > phorob.flat
gzip -k phorob.flat

EMBLmyGFF3 is version 2.1 from bioconda

Then after validating with:
java -jar webin-cli-4.1.0.jar -validate -context=genome -manifest=manifest.txt -userName=Webin-59915 -password=<pwd>


Thanks you and best wishes,

Sandro


--
Sandro Andreotti
Bioinformatics Solution Center
www.bsc.fu-berlin.de

Freie Universität Berlin
Institut für Informatik
Takustr. 9, room K21
14195 Berlin
Germany
Fon:  +49 (0)30 838-63163

**Comment by rob123king** [comment]
I'm getting the same issue with one of my submissions but can't see what is wrong? did you find out what the answer was for this? There was a similar bug 2018 that was fixed.

**Comment by rob123king** [comment]
Ive got the same issue on a second submission..

**Comment by rob123king** [comment]
Updated from 4.1.0 to 4.3.0 but still the same issue.

**Comment by rob123king** [comment]
ok another assembly submission works fine so appears something in these two other annotated genome assemblies in which this cryptic error is complaining about. I'll see if can validate one chromosome at a time and then by part to see if can work out where it is but would be good if gives a better indication of what is wrong.

**Comment by rob123king** [comment]
I've identified on one my submissions the problem is on chromosome 4 and remove half of gff file it works fine so some kind of conflict in the gff file on chromosome 4 but pass all other tool validators. the .tmp file of the embl is just the header so its some check or step in the creation of the tmp file I assume?? Any news on checking the example file given?

**Comment by Juke34** [comment]
Any update about this problem @snathanvj?

**Comment by snathanvj** [comment]
We have simplified the logic, please use the latest version and let me know if you still face this issue.
https://github.com/enasequence/webin-cli/releases/tag/v4.4.0

Background:Sorting failed because of Java version upgrade. Java 7+ uses TimSort instead of mergesort.

**Comment by snathanvj** [comment]
@Juke34 @rob123king @andreott We have simplified out sorting logic, please use the latest version and let us know if you still face this issue.
https://github.com/enasequence/webin-cli/releases/tag/v4.4.0

Background: Java7+ uses TimSort instead of Mergesort ,TimSort did not work for our existing sorting logic.
