### ISSUE TITLE
ERROR: A server error occurred when checking application version.

### ISSUE THREAD

**Issue by tk2** [enasequence/webin-cli#76]
Hi ENA colleagues,
I am running webin-cli-4.4.0 to submit read BAM files and have been getting an error about checking the application version since early this morning. Is this a bug or an issue with the server?
Rgds,
Thomas

**Comment by raskoleinonen** [comment]
We have deployed Webin-CLI version 6.0.0 with build-in FTP(S)/Aspera/HTTPS call retries and improved logging of these errors:
https://github.com/enasequence/webin-cli/releases/tag/6.0.0

This may insulate users from transient errors and will help us to diagnose the exact problem from the logs. For example, each different type of FTP(S) error can be identified from the logs.

Please upgrade to Webin-CLI version 6.0.0 and if you have further problems please contact us preferably using (fastest response time):
https://www.ebi.ac.uk/ena/browser/support
