### ISSUE TITLE
Problem of shared exons

### ISSUE THREAD

**Issue by lufuhao** [enasequence/webin-cli#8]
some genes might share exons but Webin-CLI keeps reporting 'exon duplication' errors.

**Comment by sholt6** [comment]
Hi Fu-Hao Lu,
Would be great to discuss this with you and look into making any necessary validation changes, would you mind please sending error logs and input files to us at datasubs@ebi.ac.uk ?
Best wishes,
Sam

**Comment by raskoleinonen** [comment]
Closing ticket as inactive.
