### ISSUE TITLE
ERROR: Invalid submission account user name or password

### ISSUE THREAD

**Issue by ireneortega** [enasequence/webin-cli#82]
I run the following command with  webin-cli-5.0.0.jar I've just downloaded:
```
$ java -jar webin-cli-5.0.0.jar -context genome -manifest manifestH660.txt -userName Webin-xxxx -password xxxxx -submit
INFO : Your application version is 5.0.0
...
INFO : The submission has been validated successfully.
ERROR: Invalid submission account user name or password. Please try enclosing your password in single quotes. Failed to upload files to webin.ebi.ac.uk because of a user error.
ERROR: Invalid submission account user name or password. Please try enclosing your password in single quotes. Failed to upload files to webin.ebi.ac.uk because of a user error.
```

My password does not contain any special character and I can log in the ENA Browser without problems with the same User Name and Password. However, I run again the command enclosing my password in single quotes and I got the same error. The error is not present if I use `-validate`. What's the problem? I can't upload my genomes.

**Comment by vloux** [comment]
Same error for me. It seems better this morning (october 6th)as the tool succed to authenticate  but upload is really slow.

**Comment by raskoleinonen** [comment]
We have deployed Webin-CLI version 6.0.0 with build-in FTP(S)/Aspera/HTTPS call retries and improved logging of these errors:
https://github.com/enasequence/webin-cli/releases/tag/6.0.0

This may insulate users from transient errors and will help us to diagnose the exact problem from the logs. For example, each different type of FTP(S) error can be identified from the logs.

Please upgrade to Webin-CLI version 6.0.0 and if you have further file upload problems please contact us preferably using (fastest response time):
https://www.ebi.ac.uk/ena/browser/support
