### ISSUE TITLE
Issue running behind proxy

### ISSUE THREAD

**Issue by seretol** [enasequence/webin-cli#9]
webin cli 1.6.0 doesn't seem to work when behind a proxy even when specifying the https.proxyHost and https.proxyPort properties.
I ran the following:
java -Dhttps.proxyHost=<host> -Dhttps.proxyPort=<port> -jar webin-cli-1.6.0.jar -test -context genome -userName <user> -password <pass> -inputDir <input> -outputDir <output> -validate -manifest <manifest> -submit

I get a ConnectionTimeoutException at the point it tries to verify the version of cli

**Comment by raskoleinonen** [comment]
Could you please check if you can curl successfully to the version check endpoint with and without --proxy option:

https://www.ebi.ac.uk/ena/submit/drop-box/check_version/cli/1.6.0

This should return "true".

**Comment by seretol** [comment]
Tks for your reply.

Yes, I tried curl and it works fine.  We can actually submit using the programmatic method (ie curl).

I could not rebuild the whole project locally, but was able to build just enough to execute the version check independently

In 1.6.0, I isolated the Version class and I cannot make it work behind proxies.
However, in  1.6.1 there was a significant change, and in this one, I isolated the VersionService and this one seems to work fine behind proxies
Note that there is no download of 1.6.1 so I could not check the full webin cli.

So I think it’s an issue with the underlying libraries used to make the http get calls in 1.6.0 (and prior, I tried 1.5.4 and that didn’t work either)

Best,

-oli

**Comment by raskoleinonen** [comment]
Ok, good to know that 1.6.1 worked. We are preparing to release 1.7.0 today or tomorrow that will have the same version checking code as we had in 1.6.1. We had to remove 1.6.1 because it had a fatal genome assembly validation bug (now fixed for 1.7.0 deployment).

**Comment by raskoleinonen** [comment]
We have now released Webin-CLI 1.7.0:

https://github.com/enasequence/webin-cli/releases/tag/v1.7.0

Could you please give it a try?

**Comment by seretol** [comment]
Problem solved! Many thanks.

Best,

-oli
